
name: FinRadar-devops

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-devops
    user: root # Required to access the host's Docker socket without sudo errors
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # Mount the Docker socket so Jenkins can build images and run containers
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/var/jenkins_home/.kube:ro
    networks:
      - devops_net
    restart: unless-stopped

  sonarqube:
    image: sonarqube:9.9.4-community # Stable LTS Community Edition
    container_name: sonarqube-devops
    ports:
      - "9000:9000"
    environment:
      # Disabling bootstrap checks allows SonarQube to run easily in non-production Docker setups
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - devops_net
    restart: unless-stopped

volumes:
  jenkins_home:
    name: FinRadar_jenkins_home
  sonarqube_data:
    name: FinRadar_sonarqube_data
  sonarqube_extensions:
    name: FinRadar_sonarqube_extensions
  sonarqube_logs:
    name: FinRadar_sonarqube_logs

networks:
  devops_net:
    name: FinRadar_devops_net
    driver: bridge
